// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_heat from './routes/api/heat.ts';
import * as $api_snow from './routes/api/snow.ts';
import * as $blog_automatisert_testing from './routes/blog/automatisert_testing.tsx';
import * as $blog_codeaholic from './routes/blog/codeaholic.tsx';
import * as $blog_gold_or_led from './routes/blog/gold_or_led.tsx';
import * as $blog_invester_i_produktet from './routes/blog/invester-i-produktet.tsx';
import * as $blog_painting_2025_aug_oct from './routes/blog/painting/2025-aug-oct.tsx';
import * as $blog_painting_2025_nov_dec from './routes/blog/painting/2025-nov-dec.tsx';
import * as $blog_painting_index from './routes/blog/painting/index.tsx';
import * as $blog_skiguide from './routes/blog/skiguide.tsx';
import * as $index from './routes/index.tsx';

import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/api/heat.ts': $api_heat,
    './routes/api/snow.ts': $api_snow,
    './routes/blog/automatisert_testing.tsx': $blog_automatisert_testing,
    './routes/blog/codeaholic.tsx': $blog_codeaholic,
    './routes/blog/gold_or_led.tsx': $blog_gold_or_led,
    './routes/blog/invester-i-produktet.tsx': $blog_invester_i_produktet,
    './routes/blog/painting/2025-aug-oct.tsx': $blog_painting_2025_aug_oct,
    './routes/blog/painting/2025-nov-dec.tsx': $blog_painting_2025_nov_dec,
    './routes/blog/painting/index.tsx': $blog_painting_index,
    './routes/blog/skiguide.tsx': $blog_skiguide,
    './routes/index.tsx': $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
